### ISSUE TITLE
Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by DogsAreTheShit** [InsightfulSummer/Zane-Chat-App#3]
##Error message
[Vue warn]: Error in created hook: "TypeError: Cannot read property 'emit' of undefined"

found in

---> <Layouts/default.vue> at layouts/default.vue
       <Root>

**Comment by anewage** [comment]
You need to implement the Socket.io to your code properly.
Take a look at this example: https://github.com/InsightfulSummer/vartta-web/blob/dev/lib/socket.io.js

If I want to be precise, take a look at the repo that we have right here, the following files:
- Adding it as a dependency: `yard add socket.io-client` https://github.com/InsightfulSummer/vartta-web/blob/dev/package.json
- Writing a plugin for Socket.io: https://github.com/InsightfulSummer/vartta-web/blob/dev/lib/socket.io.js
- Importing the plugin and using it: https://github.com/InsightfulSummer/vartta-web/blob/dev/layouts/default.vue

**Comment by DogsAreTheShit** [comment]
Steps taken: 
1. while in the proper directory, entered 'npm add socket.io-client' into the terminal
2. added socket.io dependency to package.json file
<img width="320" alt="Screen Shot 2020-06-04 at 10 30 31 PM" src="https://user-images.githubusercontent.com/65428292/83830383-01562100-a6b3-11ea-92a5-3bd92e5bacb7.png">
3. added 'socket.io.js file to the '/lib/' folder 
<img width="435" alt="Screen Shot 2020-06-04 at 10 31 51 PM" src="https://user-images.githubusercontent.com/65428292/83830456-306c9280-a6b3-11ea-8ae2-05e4a1a4ac57.png">
4. Added the line 'import socket from '../lib/socket.io'' to default.vue in <script> section
<img width="517" alt="Screen Shot 2020-06-04 at 10 33 58 PM" src="https://user-images.githubusercontent.com/65428292/83830565-7b86a580-a6b3-11ea-8093-93acb494db62.png">

Seems an error is being thrown so I've done something wrong. Looking into it
<img width="564" alt="Screen Shot 2020-06-04 at 10 35 21 PM" src="https://user-images.githubusercontent.com/65428292/83830669-ad980780-a6b3-11ea-8f0b-555be1bdbfa4.png">

Pushing project with updates now
