### ISSUE TITLE
now.sh not receiving the build files in the output directory

### ISSUE THREAD

**Issue by DogsAreTheShit** [InsightfulSummer/Zane-Chat-App#4]
I ran npm run build to check that the files are being properly created and they are, so I'm guessing the issue is that the location of these build files are not properly specified in now.sh. 
**Image of my build & development settings**
![Screen Shot 2020-06-07 at 1 38 06 PM](https://user-images.githubusercontent.com/65428292/83975864-1fdf3680-a8c4-11ea-9ccb-5eb557c70e5b.png)
Output directory is set to 'dist' which if i remember correctly is correct, so the issue could be with my project not putting the build files in dist

**Image of  _npm run build_  result**
<img width="605" alt="npm run build result" src="https://user-images.githubusercontent.com/65428292/83975900-5f0d8780-a8c4-11ea-9a52-3b911b79d8bc.png">

**Comment by anewage** [comment]
Did running `npm run generate` and `npm run build` create a runnable application (HTML files) inside your _dist_ folder on your local computer? Did you try openning those HTML files to see if the app is working?

**Comment by DogsAreTheShit** [comment]
I think im having the same issue that Isuri had, which is when you try and enter a name and room number, the next behind it doesnt go away, and entering the room does nothing

**Image of generated html page in dist folder**
![Screen Shot 2020-06-07 at 1 57 37 PM](https://user-images.githubusercontent.com/65428292/83976243-db08cf00-a8c6-11ea-832e-cdb8abf9cae5.png)

**Comment by anewage** [comment]
This is because the code that you are using is outdated and uses deprecated methods. You need to take a look inside `pages/index.vue` and see how they want to move from one page to the other inside function `submit`.

In order to fix this you need to change the code and look into the details of nuxt links and search for _redirect_.

**Comment by DogsAreTheShit** [comment]
Should I change my router.base to /chat?

**Comment by DogsAreTheShit** [comment]
or just create the hook modules,  render hooks etc

**Comment by DogsAreTheShit** [comment]
This is what I found:

Here is the submit function. The line: **        this.$router.push("/chat");
**  is where the user is redirected to the chat room

![Screen Shot 2020-06-07 at 7 23 36 PM](https://user-images.githubusercontent.com/65428292/83982381-6482c600-a8f4-11ea-8bc4-d3a254f821be.png)

And I believe this is what you wanted me to implement instead of the given code above:
![Screen Shot 2020-06-07 at 7 28 10 PM](https://user-images.githubusercontent.com/65428292/83982502-099d9e80-a8f5-11ea-8498-1834a9e9e37b.png)

Where I am getting confused is on how to implement that solution into my existing method (written in JS), with the solution I mentioned above, which is in HTML

Looking into it now

**Comment by DogsAreTheShit** [comment]
redirect
